<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brp.Core\Brp.Core.csproj" />
    <ProjectReference Include="..\Brp.Rules\Brp.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ability-ruleset.json" />
    <EmbeddedResource Include="skill-ruleset.json" />
    <EmbeddedResource Include="character-creation-ruleset.json" />
    <EmbeddedResource Include="background-packages.json" />
    <EmbeddedResource Include="experience-ruleset.json" />
    <EmbeddedResource Include="weapon-ruleset.json" />
    <EmbeddedResource Include="armor-ruleset.json" />
    <EmbeddedResource Include="range-band-ruleset.json" />
    <EmbeddedResource Include="combat-round-ruleset.json" />
  </ItemGroup>

</Project>
