<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brp.Core\Brp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ability-ruleset.json" />
  </ItemGroup>

</Project>
